### ISSUE TITLE
Allow photo/media uploads in replies and reposts

### ISSUE THREAD

**Issue by gijswijs** [barryf/micropublish#100]
Replies and reposts can contain photos too.

It would be appreciated if micropublish would allow for photos to be added to these type of posts too.

**Comment by barryf** [comment]
By default Micropublish doesn't expose the photo field for those two post types, but it's possible to do this via your Micropub server. If your endpoint responds to a `?q=post-types` request with the properties you want to use, the interface will be customised.

This is currently an [unofficial Micropub extension](https://github.com/indieweb/micropub-extensions/issues/8) and may change, but I use it with my server. Here's my example with the expected format: https://github.com/barryf/vibrancy/blob/master/src/http/get-micropub/config/post-types.js

**Comment by gijswijs** [comment]
But https://micropublish.net doesn't request that endpoint right now, am I right?

**Comment by barryf** [comment]
I've checked and it's actually looking for `post-types` in the config query from your endpoint.

**Comment by gijswijs** [comment]
Ah, that makes sense. I only implemented the `post-types` query response, but now I also return `post-types` inside the `config` response. After logging out and logging in again, it indeed seems to work!
![image](https://user-images.githubusercontent.com/7912094/168408810-3ab88a7b-93d4-44a0-96c8-61aaea40036b.png)

**Comment by barryf** [comment]
Thanks for the screenshot - it's nice to see how you've configured it 😄

**Comment by gijswijs** [comment]
👍

[](https://brid.gy/publish/github?bridgy_omit_link=true)
