### ISSUE TITLE
Randomly hangs when replying to ActivityPub posts

### ISSUE THREAD

**Issue by hacdias** [barryf/micropublish#109]
If you try to reply to an ActivityPub post (Pleroma, Mastodon, or even my website), the website hangs via the bookmarklet and when submitting. I'm not sure if it's related to ActivityPub posts, but it **only happens** with replies. It feels extremely random and I can't pinpoint the reason.

**Comment by barryf** [comment]
Sorry about that, @hacdias. I was also getting an occasional hang on micropublish.net but not locally. I've restarted the Render instance and that seems to have solved it.

**Comment by hacdias** [comment]
@barryf thanks! Thought it could've been a bug. Happy it isn't!
