### ISSUE TITLE
Can’t modify an existing post

### ISSUE THREAD

**Issue by paulrobertlloyd** [barryf/micropublish#111]
On the dashboard, under ‘Modify an existing post’, I enter the following URL:

```
https://paulrobertlloyd.com/notes/1670453319/
```

I get a ‘Something went wrong’ page, with the following error:

```
undefined method `key?' for nil:NilClass
```

It appears that this form is attempting to make a request to my Micropub endpoint. This provides the following response:

```jsonc
// GET https://kit.paulrobertlloyd.com/micropub
//     ?q=source
//     &url=https://paulrobertlloyd.com/notes/1670453319/

{
  "items": [
    {
      "type": [
        "h-entry"
      ],
      "properties": {
        "content": [
          {
            "html": "<p>Just read that there’s another <em>Motherland</em> Christmas special this year, airing 23 December on BBC One. This is truly excellent news!</p>",
            "value": "Just read that there’s another _Motherland_ Christmas special this year, airing 23 December on BBC One. This is truly excellent news!"
          }
        ],
        "name": [
          ""
        ],
        "post-status": [
          "published"
        ],
        "mp-syndicate-to": [
          "https://web.archive.org/"
        ],
        "published": [
          "2022-12-07T22:48:39.115Z"
        ],
        "mp-slug": [
          "3yacw"
        ],
        "post-type": [
          "note"
        ],
        "url": [
          "https://paulrobertlloyd.com/notes/1670453319/"
        ],
        "syndication": [
          "https://mastodon.social/@paulrobertlloyd/109474833616087287",
          "https://twitter.com/paulrobertlloyd/status/1600623663425851392"
        ]
      }
    }
  ]
}
```

Is this not the response Micropublish is expecting, or is there something missing?

**Comment by barryf** [comment]
Micropublish's error message isn't very helpful, is it? Sorry about that. 

What I think is the problem is that your post is contained within an `items` array. When you use the `url` parameter to find exactly one post the [spec](https://micropub.spec.indieweb.org/#source-content-p-3) says you need a top-level `properties` object and optional `type`.

Here's what my server responds with to a `?q=source&url=xyz` request: https://barryfrost.com/2022/12/week-67-tree?mf2json

**Comment by paulrobertlloyd** [comment]
Ah, damn it. I had that working correctly before, but broke it again somewhere down the line. Thanks for the quick reply – all fixed on my end now.

**Comment by paulrobertlloyd** [comment]
Aw, thanks! 😊 Very much inspired by what you and others in the community are doing.
