### ISSUE TITLE
How do I post a nested mf2 object?

### ISSUE THREAD

**Issue by aaronpk** [barryf/micropublish#15]
The [implementation report](https://github.com/w3c/Micropub/blob/master/implementation-reports/micropublish.md) says that Micropublish can create a post with a nested Microformats2 object. I don't see anything in the interface that supports this. How can I do this?

**Comment by barryf** [comment]
Hmm. I don't think that's right. Perhaps I was thinking of `content[html]` when filling out the report. I'll update the report in that case. 

Current status with the client tests: https://micropub.rocks/client/jnTeUXAPcR8gLvr1

**Comment by aaronpk** [comment]
ah okay. Those micropub.rocks links aren't public. Did you run through the test suite with micropublish already? How did the results compare to your submitted report?

**Comment by barryf** [comment]
I think they're all fine. Without photo support I'm unable to complete the full set but otherwise it should match. As you point out, there's no support for a nested mf2 object (test 204). How have you implemented that with Quill? Locations?

**Comment by aaronpk** [comment]
Quill supports posting h-reviews, with a nested h-product. Also the travel plans are nested mf2 objects but that vocab is completely experimental. The h-review vocab is documented here http://microformats.org/wiki/h-review

**Comment by barryf** [comment]
I've pushed an update that includes a new "Check-in" type with a location field that uses a nested `h-geo` object. 

It successfully creates check-ins on my dev server and now passes the Micropub.rocks 204 test.

**Comment by barryf** [comment]
Correction: I'm using h-card so I can have a `name` property. And that's now live.
