### ISSUE TITLE
Logging in with "commentpara.de" does not work / wrong user URL

### ISSUE THREAD

**Issue by cweiske** [barryf/micropublish#19]
When logging in with https://commentpara.de/, a user URL of `https://commentpara.de/user/3.htm` is returned to the micropub client. Quill does this correctly.

Micropublish only uses only the originally input `http://commentpara.de` as the user name, leading to a post error:

> There was an error making a request to your Micropub endpoint. The error received was: {"error":"forbidden","error_description":"Invalid user URL"}

Micropublish should use the final me URL, not the user-input one.

**Comment by cweiske** [comment]
The issue does still exist. I described it in detail at https://github.com/cweiske/anoweco/issues/3#issuecomment-323453289

Looking at the micropublish code in `server.rb` I see that you do the same as quill seems to do: You ignore the "me" returned to the callback because of https://github.com/aaronpk/Quill/issues/79 but do not do auth code verification, which would give you the new `me` in a secure way.

So you call the token endpoint with the old `me` and not the new one. Previously the token endpoint would just return the `me` you passed, but now it rejects those requests because the `me` attached to the auth code does not match the `me` you're passing to me.

**Comment by cweiske** [comment]
Discussion about that: https://chat.indieweb.org/dev/2017-08-18#t1503089497099000

**Comment by cweiske** [comment]
https://indieweb.org/File:micropub-auth-flow.png suggests step 3 is never executed. Discussion with @aaronpk suggests that the token endpoint should ignore the `me` parameter at all and return the `me` associated with the code.

**Comment by cweiske** [comment]
So I have to adjust my code.

**Comment by barryf** [comment]
@cweiske So if I follow the discussion, if you change your token endpoint so that it gives the `me` associated with the code, that should now work. Does that work for you?

**Comment by cweiske** [comment]
Am 19. August 2017 16:37:42 MESZ schrieb Barry Frost <notifications@github.com>:
>@cweiske So if I follow the discussion, if you change your token
>endpoint so that it gives the `me` associated with the code, that
>should now work. Does that work for you?

Yes, that works fine.
-- 
Christian
