### ISSUE TITLE
Allow removal of in-reply-to when editing

### ISSUE THREAD

**Issue by martymcguire** [barryf/micropublish#20]
Hey there! Thank you for micropublish! I use it heavily to edit my posts to add syndication links. :}

I recently made a post with an in-reply-to URL. I wanted to change that to a simple mention, with the URL in the body. However, when I blank the in-reply-to field during an edit, micropublish won't let me submit the form, asking me to please enter a value for that field.

Expected behavior: micropublish detects the change and sends a micropub edit request to remove that attribute from the post.

Thanks again!

**Comment by barryf** [comment]
Hey @martymcguire. Thanks for using it! 

You've found one of the areas I'd like to change: the hard-coded post types which can't be altered when editing. 

The workaround I use is the "Edit All" button from the dashboard which gives you an interface where all fields are available but none are required. You can remove the `in-reply-to` field using this form.

Does that work for your use case?

**Comment by martymcguire** [comment]
Oh, that is lovely! I had not thought to try "Edit All". That should work just fine!

Since you're planning some larger changes that would sweep this one up, I'll consider this closed for now and use the workaround. :}

Thanks again!

**Comment by barryf** [comment]
Great! Thanks, @martymcguire.
