### ISSUE TITLE
Use full URL for client_id

### ISSUE THREAD

**Issue by aaronpk** [barryf/micropublish#3]
If you use a full URL for `client_id`, then you can get the IndieAuth server to show app info during authorization! Use h-x-app markup to point to the app's name and logo. https://indiewebcamp.com/h-x-app

**Comment by barryf** [comment]
I hadn't seen h-x-app: thanks, shouldn't be hard to include that markup.

**Comment by barryf** [comment]
Added `h-x-app` markup and switched client_id to be the base URL. Now showing up in IndieAuth process.
