### ISSUE TITLE
Raw content instead of HTML for Articles

### ISSUE THREAD

**Issue by hacdias** [barryf/micropublish#42]
Hello 👋

I've been using Micropub for months and using micropublish.net to publish all my microinteractions. However, I never use the Articles publishing feature because I simply don't want to write HTML. It would be nice to be able to choose between editing HTML or just raw content.

I haven't looked at the code, but I could probably work on implementing that if that's something that'd be welcome!

**Comment by barryf** [comment]
Hey @hacdias. That's a fair suggestion and one I'd be happy to support. I think I'd also find that useful for when I want to write Markdown articles.

**Comment by hacdias** [comment]
Omg, you implemented it @barryf! Thank you so much. I guess I won't need to do it next weekend then!
