### ISSUE TITLE
PKCE Validation Failure

### ISSUE THREAD

**Issue by dshanske** [barryf/micropublish#58]
Tried your code with my WordPress endpoint and am getting a PKCE validation failure. I've had PKCE for a while and it does work with other PKCE clients.

**Comment by jamietanna** [comment]
@barryf is resolving this now! https://github.com/barryf/micropublish/commit/ea346308a50143faad9e9a14ebdb2b68ee3db228 should resolve it, just waiting for it to be deployed :+1:

**Comment by barryf** [comment]
Hey @dshanske! Thanks for testing. ea34630 has been deployed now. Would you mind trying again?

**Comment by jamietanna** [comment]
I'm still seeing 400s, just trying to step through manually to verify what's going wrong :+1:

**Comment by barryf** [comment]
Ah. I'll take a closer look.

**Comment by barryf** [comment]
For reference:

https://tools.ietf.org/html/rfc7636#appendix-A

**Comment by barryf** [comment]
There's a new release on a temporary staging URL with a fix that passes the example in the RFC. 

If you've got time to check @jamietanna or @dshanske then would you mind trying: https://mpubl-br-master.herokuapp.com/

**Comment by jamietanna** [comment]
LGTM! I've authenticated successfully 🙌

**Comment by barryf** [comment]
Awesome! Thanks @jamietanna 😄 

I had found an implementation in Ruby that I now realise didn't work and copied it over. Lesson learned! 

As well as the IndieAuth changes I've also added support for properties via `q=config` which I think your server supports. Does it work for your config?

**Comment by barryf** [comment]
Closing this issue following successful authorisations using three separate servers.
