### ISSUE TITLE
Autoconfiguration of fields requires manually editing the `published` property

### ISSUE THREAD

**Issue by jamietanna** [barryf/micropublish#59]
Now we've added support for autoconfiguration, I've spotted that when publishing a note (which has a required `published` property) it requires the user to fill it out, rather than it be auto-generated - is that expected?

**Comment by barryf** [comment]
Yes, that's intentional. My server doesn't include `published` in its config properties and sets the value to "now" on create if it's blank.

I can see the argument for your approach however. Are there any other examples out there?

**Comment by jamietanna** [comment]
That makes sense - I wonder if we could have Micropublish fill in `published` by the current date, on page generation?

**Comment by barryf** [comment]
I guess the issue with setting a published date on page load is that there will be a time delay between loading the page and then publishing the post.

However I'm happy to set a default value to an ISO 8601 timestamp in UTC, e.g. `2021-02-09T09:50:24Z`, if that's useful to you.
