### ISSUE TITLE
call to verify auth code sends an empty client_id

### ISSUE THREAD

**Issue by kylewm** [barryf/micropublish#8]
I'm seeing this in the error log for silo.pub

```
2015-07-28 01:06:33,459 - feverdream.app - WARNING - client_id mismatch. expected=https://micropublish.herokuapp.com, received=
```

also I don't think it's necessary to verify the auth code against the authorization endpoint (and it's not actually required for authorization endpoints to support verification for micropub). You can just skip right to asking the token endpoint for a token.

**Comment by barryf** [comment]
Sorry about this @kylewm. Just reading up on Fever Dream -- looks fantastic! I've pushed a fix to
my Heroku instance and can now log in with a test Tumblr blog. Works like magic. Does this also
fix it for you?

Also, thanks for the pointer on my over-fussy auth approach. I'll take a look. I've been meaning to
make some changes to reflect Micropub's recent improvements so will re-read the wiki and docs to
make Micropublish behave properly.

**Comment by kylewm** [comment]
Nice, that totally worked! Thanks for the quick fix!
