### ISSUE TITLE
Support Location

### ISSUE THREAD

**Issue by hacdias** [barryf/micropublish#84]
Hey - it would be really nice if Micropublish supported adding location to posts similar to Quill. Unfortunately Quill only adds Location to notes, but it'd be great if that was an option for all post types. 😃

**Comment by barryf** [comment]
Thanks for the issue, @hacdias! The hosted version at Micropublish.net has a default list for each post type with a fairly standard set of properties, but there are two methods you could use if you wanted to show the location fields:

1. Clone the Micropublish repo and run your own instance. You can then customise the config/properties.json file and add `location` to other post types.
2. Update your Micropub server to specify the properties you want. This is a proposed Micropub extension[^1] to return a JSON object with specific properties and required-properties when a client requests `?q=post-types`. For example, this is what my server sends: https://github.com/barryf/vibrancy/blob/master/src/http/get-micropub/config/post-types.js

[^1]: https://github.com/indieweb/micropub-extensions/issues/33

**Comment by hacdias** [comment]
Thanks for the reply @barryf!

1. That could be an option. I'll try that out. Would it also have the same "Find" functionality that you can see on Check-in?
2. I didn't know about that extension and it looks very cool!

**Comment by hacdias** [comment]
@barryf I added location to note via the method you linked, but it does not show up. I tried removing other fields and that worked. But adding location did not.

**Comment by barryf** [comment]
@hacdias My mistake - it's been a while since I wrote that logic! The location fields are nested within the `checkin` property as an h-card. I'll re-open this issue as an enhancement.
