### ISSUE TITLE
Client ID must have a path

### ISSUE THREAD

**Issue by hacdias** [barryf/micropublish#88]
Hey!

According to the [spec](https://indieauth.spec.indieweb.org/#client-identifier), a client identifier must contain a path (emphasis added):

> Clients are identified by a [URL]. Client identifier URLs MUST have either an https or http scheme, **MUST contain a path component,** MUST NOT contain single-dot or double-dot path segments, MAY contain a query string component, MUST NOT contain a fragment component, MUST NOT contain a username or password component, and MAY contain a port. Additionally, host names MUST be domain names or a loopback interface and MUST NOT be IPv4 or IPv6 addresses except for IPv4 127.0.0.1 or IPv6 [::1].

It is not a problem for me, but I bumped into someone that could not log in in Micropublish because they were strictly verifying that 😃   Perhaps it would be great to add that [here](https://github.com/barryf/micropublish/blob/52933b6b5b67ba8267ba9f0d7230b04e83d5d117/lib/micropublish/auth.rb#L10).

**Comment by barryf** [comment]
Micropublish identifies itself using `base_url` from the request, which in the case of the version hosted at Micropublish.net is "https://micropublish.net" -- without the trailing slash. Looks like it needs that path element to conform to the spec. I'll get that updated.

Out of interest, whose client was failing to log in?

**Comment by hacdias** [comment]
It was @sebsel. I also updated my IndieAuth verifications to be compliant to the spec today. Is it deployed already? Because it's failing here with `client_id differs` so I want to check if I made some mistake 😰

**Comment by barryf** [comment]
There was another place where the / was needed, but it should now be deployed.

**Comment by hacdias** [comment]
It does work! Thanks!
